Controllers/DataViewToControllerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestProject_MVC.Models;

namespace TestProject_MVC.Controllers
{
    public class DataViewToControllerController : Controller
    {
        // GET: DataViewToControlle
        [Route("viewToController")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string UsingParameter(int EmployeeNo, string EmployeeName)
        {
            return "Data from parameters - ID :" + EmployeeNo + ", Name : " + EmployeeName;
        }

        [HttpPost]
        public string UsingRequest()
        {
            return "Data from Request - ID :" + Request["EmployeeNo"] + ", Name : " + Request["EmployeeName"];
        }

        [HttpPost]
        public string UsingFormCollection(FormCollection form)
        {
            return "Data from FormCollection - ID :" + form["EmployeeNo"] + ", Name : " + form["EmployeeName"];
        }

        public string UsingStronglyBinding(Employee emp)
        {
            return "Data from Strongly Binding - ID :" + emp.EmployeeID + ", Name : " + emp.EmployeeName;
        }
    }
}

Controllers/InsertDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test_MVC.Model;
using Test_MVC.db.dbOperations;
using Newtonsoft.Json;

namespace TestProject_MVC.Controllers
{
    public class InsertDataController : Controller
    {
        EmployeeRepository employeeRepository = null;
        public InsertDataController()
        { 
            employeeRepository = new EmployeeRepository();
        }
                
        public ActionResult addEmployee()
        {
            return View();
        }

        [HttpPost]
        public ActionResult addEmployee(EmploayeeModel model)
        {
            if (ModelState.IsValid)
            {
                int id = employeeRepository.AddEmployee(model);
                if (id > 0)
                {
                    ModelState.Clear();
                    ViewBag.IsSuccess = "Data Added Emp ID : " + id;

                    return RedirectToAction("getAllEmployees");
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult getAllEmployees()
        {
            var result = employeeRepository.getAllEmployee();
            return View(result);
        }

        [HttpGet]
        public ActionResult getEmployeeDetail(int id)
        {
            var result = employeeRepository.getEmployee(id);
            return View(result);
        }

        [HttpGet]
        public JsonResult getEmployeeDetailJson(int id)
        {
            var result = employeeRepository.getEmployee(id);
            var json = JsonConvert.SerializeObject(result);
            return Json(json,JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult editEmployee(int id)
        {
            var result = employeeRepository.getEmployee(id);
            return View(result);
        }

        [HttpPost]
        public ActionResult editEmployee(EmploayeeModel model)
        {
            if (ModelState.IsValid)
            {
                bool isEdit = employeeRepository.UpdateEmployee(model.employeeID, model);

                if (isEdit)
                {
                    return RedirectToAction("getAllEmployees");
                }
            }
            return View();
        }

        public ActionResult deleteEmployee(int id)
        {
            bool isDelete = employeeRepository.RemoveEmployee(id);

            if (isDelete)
            {
                return RedirectToAction("getAllEmployees");
            }

            return View();
        }
    }
}

Controllers/ViewBagViewDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestProject_MVC.Models;

namespace TestProject_MVC.Controllers
{
    public class ViewBagViewDataController : Controller
    {
        // GET: ViewBagViewData
        public ActionResult Index()
        {
            //ViewBag
            ViewBag.Name = "Shubham Dhomse";
            ViewBag.Mylist = new List<string>() { "a", "b", "c", "d" };

            List<Employee> empList = new List<Employee>()
            {
                new Employee(){ EmployeeID = 3634 , EmployeeName = "Shubham", EmployeeAddress = "Kharadi"},
                new Employee(){ EmployeeID = 3631 , EmployeeName = "Sahil", EmployeeAddress = "Kharadi"},
                new Employee(){ EmployeeID = 3514 , EmployeeName = "Prasad", EmployeeAddress = "Hadapsar"}
            };

            ViewBag.EmployeeList = empList;

            //ViewData
            ViewData["Name"] = "Dhomse Shubham";
            ViewData["Mylist"] = new List<string>() { "l", "m", "n", "o" };
            //ViewBag["EmployeeList"] = empList; //not working


            //TempData
            TempData["mobileNo"] = "8369791005";
            

            return View();
        }

        public ActionResult SecondCall()
        {
            //ViewBag.MobileNo = TempData["mobileNo"]; //this line only read tempdata

            //TempData.Keep(); // It store all temp data

            //TempData.Keep("mobileNo"); //// It store spesific key data

            ViewBag.MobileNo = TempData.Peek("mobileNo"); // this read aswel as keep the data

            return View();
        }

        public ActionResult ThirdCall()
        {
            ViewBag.MobileNo = TempData["mobileNo"];
            return View();
        }
    }
}

Controllers/renderPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestProject_MVC.Controllers
{
    public class renderPageController : Controller
    {
        // GET: renderPage
        public ActionResult Index()
        {
            return View();
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <style>
        .body-content {
            padding:0 !important;
        }
    </style>
</head>
<body style="margin:0 !important">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div>
            <div style="width:100%;position:fixed;height:50px;padding:5px;background-color:#5c5c5c;top:0;">
                <table width="100%" cellpadding="5" align="center">
                    <tr>
                        <td width="30%"><span style="font-size:22px;font-weight:bold;color:white;text-shadow: 2px 2px #000000">MVC Test App</span></td>
                        <td width="10%" valign="middle" align="center" style="border-right:1px solid #ffffff">
                            <a>@Html.ActionLink("HTML Helpers", "Index", "Home", null, new { style = "color:white;font-weight:bold;text-decoration:none" }) </a>
                        </td>
                        <td width="10%" valign="middle" align="center" style="border-right:1px solid #ffffff">
                            <a>@Html.ActionLink("ViewBag - ViewData", "Index", "ViewBagViewData", null, new { style = "color:white;font-weight:bold;text-decoration:none" }) </a>
                        </td>
                        <td width="10%" valign="middle" align="center" style="border-right:1px solid #ffffff">
                            <a>@Html.ActionLink("Routing", "getAllEmployee", "Routing", null, new { style = "color:white;font-weight:bold;text-decoration:none" }) </a>
                        </td>
                        <td width="10%" valign="middle" align="center" style="border-right:1px solid #ffffff">
                            <a>@Html.ActionLink("View To Controller", "Index", "DataViewToController", null, new { style = "color:white;font-weight:bold;text-decoration:none" }) </a>
                        </td>
                        <td width="10%" valign="middle" align="center" style="border-right:1px solid #ffffff">
                            <a>@Html.ActionLink("Validation", "Index", "Validation", null, new { style = "color:white;font-weight:bold;text-decoration:none" }) </a>
                        </td>
                        <td width="10%" valign="middle" align="center" style="border-right:1px solid #ffffff">
                            <a>@Html.ActionLink("Render Page", "Index", "renderPage", null, new { style = "color:white;font-weight:bold;text-decoration:none" }) </a>
                        </td>
                        <td width="10%" valign="middle" align="center" style="border-right:1px solid #ffffff">
                            <a>@Html.ActionLink("Entity FrmWrk", "getAllEmployees", "InsertData", null, new { style = "color:white;font-weight:bold;text-decoration:none" }) </a>
                        </td>
                    </tr>
                </table>
            </div>
            <div style="width:100%;background-color:lightyellow;padding:1px;text-align:center;margin-top:40px;">
                @*@RenderSection("pageHeading", required: true)*@
                @RenderSection("pageHeading", required: false)
                @*If we set required - true then we need to set that section to every chiled view*@
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div style="margin:70px 50px">
            @RenderBody()
        </div>
        <hr />
        <footer>
            @RenderSection("footerFromAnyPage", required: false)
            @*If we set required - false then no need to set that section to every chiled view*@
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>