Controllers/custValidationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestProject_MVC.Models;


namespace TestProject_MVC.Controllers
{
    public class custValidationController : Controller
    {
        // GET: custValidation
        [Route("customeValidation")]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult validate(Department dpt)
        {
            if (ModelState.IsValid)
            {
                ModelState.Clear();
                return View();
            }
            return View("Index");
        }
    }
}

Views/custValidation/Index.cshtml
@model TestProject_MVC.Models.Department
@{
    ViewBag.Title = "submitData";
}

<style>
    .field-validation-error {
        color: red;
    }
</style>


@section pageHeading
{
    <div style="width:100%;background-color:lightyellow">
        <h2>Custome Validation</h2>
    </div>
}

@using (Html.BeginForm("validate", "custValidation", FormMethod.Post))
{
    <span>Department ID : </span> @Html.EditorFor(y => y.DepartmentID)
    <br />
    @Html.ValidationMessageFor(y => y.DepartmentID)
    <br />
    <br />

    <span>Name : </span>@Html.TextBoxFor(y => y.DepartmentName)
    <br />
    @Html.ValidationMessageFor(y => y.DepartmentName)
    <br />
    <br />

    <input type="submit" value="Save" />
}

Views/custValidation/validate.cshtml
@{
    ViewBag.Title = "validate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>validate</h2>