Controllers/ValidationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestProject_MVC.Models;


namespace TestProject_MVC.Controllers
{
    public class ValidationController : Controller
    {
        // GET: Validation
        [Route("validation")]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SubmitData(Employee emp)
        {
            if(ModelState.IsValid)
            {
                return View();
            }
            return View("Index");
        }        

    }
}

Controllers/customeValidationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestProject_MVC.Models;
using System.ComponentModel.DataAnnotations;

namespace TestProject_MVC.Controllers
{
    public class customeValidationController : Controller
    {
        // GET: customeValidation
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult validation(Department dpt)
        {
            if (ModelState.IsValid)
            {
                ModelState.Clear();
                return View();
            }
            return View("Index");
        }
    }    
}

Views/Validation/Index.cshtml
@model TestProject_MVC.Models.Employee
@{
    ViewBag.Title = "Index";
}

<style>
    .field-validation-error {
        color: red;
    }
</style>

@section pageHeading
{
    <div style="width:100%;background-color:lightyellow">
        <h2>Validation</h2>
    </div>
}




<div>
    <h3>1] Loosely Binding</h3>
    <br />

    @using (Html.BeginForm("SubmitData", "Validation", FormMethod.Post))
    {
        <span>Employee No : </span> @Html.Editor("EmployeeID")<br />
        @Html.ValidationMessage("EmployeeID", new { @class = "text-danger" })<br /><br />
        <span>Name : </span>@Html.TextBox("EmployeeName")<br />
        @Html.ValidationMessage("EmployeeName", new { @class = "text-danger" })<br /><br />
        <span>Email : </span>@Html.TextBox("EmployeeEmail")<br />
        @Html.ValidationMessage("EmployeeEmail", new { @class = "text-danger" })<br /><br />
        <span>Mobile : </span>@Html.TextBox("EmployeeMobile")<br />
        @Html.ValidationMessage("EmployeeMobile", new { @class = "text-danger" })<br /><br />
        <span>DOB : </span>@Html.Editor("DOB")<br />
        @Html.ValidationMessage("DOB", new { @class = "text-danger" })<br /><br />

        <input type="submit" value="Save" />

    }

    <br />
    <hr />

    <h3>1] Strongly Binding</h3>
    <br />

    @using (Html.BeginForm("SubmitData", "Validation", FormMethod.Post))
    {
        <span>Employee No : </span> @Html.EditorFor(x => x.EmployeeID)<br />
        @Html.ValidationMessageFor(x => x.EmployeeID)<br /><br />

        <span>Name : </span>@Html.TextBoxFor(x => x.EmployeeName)<br />
        @Html.ValidationMessageFor(x => x.EmployeeName)<br /><br />

        <span>Email : </span>@Html.TextBoxFor(x => x.EmployeeEmail)<br />
        @Html.ValidationMessageFor(x => x.EmployeeEmail)<br /><br />

        <span>Mobile : </span>@Html.TextBoxFor(x => x.EmployeeMobile)<br />
        @Html.ValidationMessageFor(x => x.EmployeeMobile)<br /><br />

        <span>DOB : </span>@Html.EditorFor(x => x.DOB)<br />
        @Html.ValidationMessageFor(x => x.DOB)<br /><br />

        <input type="submit" value="Save" />

    }

    <hr />
    <h3>3] Validation Summery</h3>
    @Html.ValidationSummary()

    <br />
    <h3>4] Custome Validation</h3>
    @Html.ActionLink("go to custome validation", "Index", "customeValidation")
</div>

Views/Validation/SubmitData.cshtml
@{
    ViewBag.Title = "SubmitData";
}


@section pageHeading
{
    <div style="width:100%;background-color:lightyellow">
        <h2>Submit Data</h2>
    </div>
}